Update pacman.yml

diff --git a/.github/workflows/pacman.yml b/.github/workflows/pacman.yml
--- a/.github/workflows/pacman.yml
+++ b/.github/workflows/pacman.yml
@@ -1,30 +1,38 @@
-name: Generate pacman animation
+name: Pacman generator
 
 on:
+  push:
+  workflow_dispatch:
   schedule:
     - cron: "0 */12 * * *" # run every 12 hours
-  workflow_dispatch:
-  push:
-    branches:
-      - main
 
 jobs:
-  generate:
-    permissions:
-      contents: write
+  build:
     runs-on: ubuntu-latest
-    timeout-minutes: 5
-
     steps:
-      - name: Generate pacman-contribution-graph.svg
+      - name: Create pacman animation
         uses: abozanona/pacman-contribution-graph@main
         with:
-          github_user_name: ${{ github.repository_owner }}
+          # GitHub user name to read the contribution graph from (**required**)
+          # using action context var `github.repository_owner` or specified user
+          github_user_name: Guru-1205
 
-      - name: Push pacman-contribution-graph.svg to output branch
+      - name: Prepare output files
+        run: |
+          mkdir -p dist
+          if [ -f pacman-contribution-graph.svg ]; then
+            mv pacman-contribution-graph.svg dist/
+            # Duplicate to support dark mode in README <picture> tag
+            cp dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg
+          else
+            echo "❌ pacman-contribution-graph.svg not found!"
+            exit 1
+          fi
+
+      - name: Push pacman-contribution-graph.svg to the output branch
         uses: crazy-max/ghaction-github-pages@v3.1.0
         with:
           target_branch: output
-          build_dir: .
+          build_dir: dist
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
